packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  bcrypt: true
minimumReleaseAgeExclude:
  - '@nestjs/common@12.1.2'
  - '@nestjs/core@12.1.2'
  - '@nestjs/observe@0.3.5'
  - '@nestjs/platform-fastify@12.1.2'
  - '@nestjs/testing@12.1.2'
  - launder@1.7.2
  - pg-cloudflare@1.4.1
  - pg-connection-string@2.14.1
  - pg-protocol@1.16.1
  - pg@8.23.1
  - sanitize-html@2.18.0
